version: '3'
services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_PASS: "${DB_PASS}"
        DB_NAME: "${DB_NAME}"
        DB_USER: "${DB_USER}"
        DB_ROOT_PASS: "${DB_ROOT_PASS}"
    image: mariadb
    container_name: mariadb
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ".env"
    networks:
      - backend
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    volumes:
      - html:/var/www/html
    env_file:
      - ".env"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    volumes:
      - html:/var/www/html
    env_file:
      - ".env"
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odroz-ba/data/html
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/odroz-ba/data/mysql
