version: '3'

services:
web:
  image: nginx
  # container_name: nginx
  restart: always
  build: ./nginx
  volumes:
  - ./templates:/etc/nginx/templates
  ports:
  - "8080:80"
  #  - "443:80"
  environment:
  - NGINX_HOST=foobar.com
  - NGINX_PORT=80
  # entrypoint: ps aux
