version: '3'

services:
  db:
    image: mysql:5.7
    build: ./requirements/mariadb/
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    build: ./requirements/wordpress/
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  web:
    image: nginx
    # container_name: nginx
    restart: always
    build: ./requirements/nginx/
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    #  - "8080:443"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    # entrypoint: ps aux

volumes:
  db_data: {}
